M48
; DRILL file {KiCad (6.0.0)} date Wed Jun  1 09:59:36 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-01T09:59:36+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X2.5571Y-3.025
X2.5571Y-3.9602
X8.1736Y-1.9
X8.1736Y-3.9596
T2
X3.745Y-3.6809
X5.2802Y-3.8885
X5.2898Y-1.9583
T0
M30
